-- Demo task set: short, checkable tasks across fields that had none, so the
-- whole platform shows the review flow end-to-end. General rubric.
INSERT OR REPLACE INTO tasks (id, category, prompt, rubric_json, is_gold, active, status, expected_answer) VALUES
  ('tsk_rec_1', 'recruiting',
   'Write a concise first-outreach LinkedIn message (<= 120 words) to a Senior Backend Engineer for a Series B fintech, referencing one specific reason the role fits their background.',
   '[{"key":"correct","label":"Correct","description":"Matches the expected answer; nothing made up."},{"key":"useful","label":"Useful","description":"Could be sent with little rework."},{"key":"specific","label":"Specific","description":"Specific to the role, not generic."},{"key":"honest","label":"Honest","description":"No fabricated claims about the company."}]',
   0, 1, 'active', 'A short, personalized, non-spammy message under 120 words with one concrete hook and a clear ask.'),
  ('tsk_mkt_1', 'marketing',
   'Write landing-page hero copy (headline + subhead + CTA) for a B2B tool that auto-generates SOC 2 evidence. Keep the headline under 10 words.',
   '[{"key":"correct","label":"Correct","description":"On-brief and accurate."},{"key":"useful","label":"Useful","description":"Usable with light edits."},{"key":"specific","label":"Specific","description":"Specific to the product, not filler."},{"key":"honest","label":"Honest","description":"No overclaiming."}]',
   0, 1, 'active', 'A crisp headline (<10 words), a benefit-led subhead, and an action CTA — specific to SOC 2 evidence automation.'),
  ('tsk_legal_1', 'legal',
   'Flag the three riskiest clauses in a mutual NDA that has: unlimited term, no carve-out for independently developed information, and injunctive relief without bond. Explain each risk in one sentence.',
   '[{"key":"correct","label":"Correct","description":"Identifies the real risks."},{"key":"useful","label":"Useful","description":"Actionable for a non-lawyer."},{"key":"specific","label":"Specific","description":"Cites the specific clauses."},{"key":"honest","label":"Honest","description":"Flags uncertainty; not legal advice."}]',
   0, 1, 'active', 'Names the unlimited term, missing independent-development carve-out, and no-bond injunctive relief as the three risks with a one-line rationale each.'),
  ('tsk_trans_1', 'translation',
   'Translate to French, keeping a formal business tone: "Thank you for your prompt payment. Your account is now settled in full, and we look forward to continuing our partnership."',
   '[{"key":"correct","label":"Correct","description":"Accurate translation."},{"key":"useful","label":"Useful","description":"Natural, sendable."},{"key":"specific","label":"Specific","description":"Preserves tone and terms."},{"key":"honest","label":"Honest","description":"No omissions or additions."}]',
   0, 1, 'active', 'A fluent, formal French rendering that preserves meaning and tone (e.g. uses vous, correct business register).'),
  ('tsk_teach_1', 'teaching',
   'Write a 45-minute Grade 5 lesson plan objective + 3 activities for introducing fractions as parts of a whole, aligned to a "understand a fraction 1/b" standard.',
   '[{"key":"correct","label":"Correct","description":"Standards-aligned and accurate."},{"key":"useful","label":"Useful","description":"A teacher could run it."},{"key":"specific","label":"Specific","description":"Grade- and standard-specific."},{"key":"honest","label":"Honest","description":"Realistic for 45 minutes."}]',
   0, 1, 'active', 'A clear objective plus 3 concrete, age-appropriate activities that fit 45 minutes and target 1/b fractions.'),
  ('tsk_data_1', 'data_analysis',
   'Given monthly revenue [12,14,13,17,19,22,21,25] (Jan-Aug), compute the month-over-month growth rates and identify the single strongest growth month with its percentage.',
   '[{"key":"correct","label":"Correct","description":"Arithmetic is right."},{"key":"useful","label":"Useful","description":"Clear takeaway."},{"key":"specific","label":"Specific","description":"Uses the given numbers."},{"key":"honest","label":"Honest","description":"Shows the calculation."}]',
   0, 1, 'active', 'MoM rates computed correctly; strongest month is Apr (13→17 = +30.8%).'),
  ('tsk_travel_1', 'travel_planning',
   'Plan a 3-day Tokyo itinerary for a vegetarian traveler on a $150/day budget, using public transit only. Give 2-3 items per day with rough costs.',
   '[{"key":"correct","label":"Correct","description":"Real places, feasible routing."},{"key":"useful","label":"Useful","description":"Actionable plan."},{"key":"specific","label":"Specific","description":"Respects budget, diet, transit."},{"key":"honest","label":"Honest","description":"Costs are realistic."}]',
   0, 1, 'active', 'A feasible 3-day plan with real transit-accessible spots, vegetarian options, and per-day costs within ~$150.'),
  ('tsk_grant_1', 'grant_writing',
   'Draft a 150-word statement of need for a nonprofit expanding after-school STEM tutoring in a low-income district with a 40% math-proficiency rate.',
   '[{"key":"correct","label":"Correct","description":"Uses the given facts."},{"key":"useful","label":"Useful","description":"Funder-ready."},{"key":"specific","label":"Specific","description":"Cites the 40% figure and context."},{"key":"honest","label":"Honest","description":"No invented statistics."}]',
   0, 1, 'active', 'A ~150-word need statement grounding urgency in the 40% proficiency rate and the target district, without fabricated data.'),
  ('tsk_web_1', 'web_research',
   'In one cited paragraph, summarize the current consensus on whether four-day work weeks improve productivity, with at least two sources.',
   '[{"key":"correct","label":"Correct","description":"Accurate summary."},{"key":"useful","label":"Useful","description":"Balanced and clear."},{"key":"specific","label":"Specific","description":"Cites real sources."},{"key":"honest","label":"Honest","description":"No fabricated citations."}]',
   0, 1, 'active', 'A balanced paragraph citing real studies (e.g. 4 Day Week Global trials) with accurate figures.'),
  ('tsk_resume_1', 'resumes',
   'Rewrite this resume bullet to be quantified and impact-driven: "Responsible for managing the company social media accounts and posting content."',
   '[{"key":"correct","label":"Correct","description":"Preserves the role truthfully."},{"key":"useful","label":"Useful","description":"Stronger, usable bullet."},{"key":"specific","label":"Specific","description":"Adds concrete metrics/verbs."},{"key":"honest","label":"Honest","description":"No invented numbers presented as fact."}]',
   0, 1, 'active', 'An action-verb, quantified bullet (e.g. grew followers X%, drove Y engagement) that stays truthful to the original role.'),
  ('tsk_book_1', 'bookkeeping',
   'Categorize these 5 transactions (Chart of Accounts: COGS, Marketing, Software, Travel, Meals): "Google Ads $400", "AWS $220", "Uber to client $30", "Client dinner $85", "Wholesale inventory $1,200".',
   '[{"key":"correct","label":"Correct","description":"Correct categories."},{"key":"useful","label":"Useful","description":"Clean mapping."},{"key":"specific","label":"Specific","description":"Maps each line."},{"key":"honest","label":"Honest","description":"Flags any ambiguity."}]',
   0, 1, 'active', 'Google Ads→Marketing, AWS→Software, Uber→Travel, Client dinner→Meals, Wholesale inventory→COGS.'),
  ('tsk_forest_1', 'forestry',
   'A stand has 180 trees/acre, average DBH 14 in, merchantable height 48 ft. Estimate board-foot volume per acre and name the estimation method you used.',
   '[{"key":"correct","label":"Correct","description":"Reasonable estimate + method."},{"key":"useful","label":"Useful","description":"Shows the approach."},{"key":"specific","label":"Specific","description":"Uses the given measurements."},{"key":"honest","label":"Honest","description":"States assumptions."}]',
   0, 1, 'active', 'A board-foot/acre estimate naming a standard method (e.g. Doyle/Scribner/International 1/4-inch) with the calculation shown.');
